// <auto-generated />
namespace TimeSpent.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class entitymilescolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(entitymilescolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201609281405481_entity-miles-column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
